site_name: Conductor
nav:
    - Getting started: index.md
    - Fundamentals: primitives.md
    - Http Requests: http-walkthru.md
    - Custom Steps: custom-steps.md
    - API Reference: api-reference.md
    - Roadmap: roadmap.md
theme: readthedocs